name: Publish Docker image to Dockerhub

on:
  workflow_dispatch:
    inputs:
      version:
        description: Image version tag to push
        type: string
        required: true

jobs:
  push_to_registry:
    name: Push latest version to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: alfarv/best-queue
          tags: ${{ github.event.inputs.version }}
          labels: |
            org.opencontainers.image.version=${{ github.event.inputs.version }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: index.docker.io/alfarv/best-queue
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: false
